#ifndef FLASHCARD_INIT_H
#define FLASHCARD_INIT_H

#define FLASHCARD_INIT_CHANNEL FIFO_USER_03
#define FLASHCARD_INIT_REQUEST 0x54494E49 // 'INIT'
#define FLASHCARD_INIT_OK 0
#define FLASHCARD_INIT_BAD_HEADER 0x16

#endif
